### PR TITLE
Removed the white space between the toolbar and content

### PR DESCRIPTION
**Pull request by AIDEA775**
I removed the margin and put padding with clipToPadding:

screenshot_15434599222

### CODE REVIEW

**Comment by djuretic** [comment]
Great! I'll check it on the weekend :)

**Comment by djuretic** [comment]
Thanks @AIDEA775 for taking your time to to a PR for the app :smiley:, this will be included in the next update (end of December).

**Comment by AIDEA775** [comment]
Nedankinde ;)

**Comment by djuretic** [comment]
@AIDEA775 ĝisdatigu la apon =)

**Pull request merged**
